### ISSUE TITLE
Can I take over the maintenance of this repo?

### ISSUE THREAD

**Issue by simonschaufi** [earelin/php-libkml#11]
Hello, I would like to continue maintaining this repo. Would that be OK for you or do I need to fork it and release my own version?

**Comment by earelin** [comment]
I would be happy if you wanted to maintain this repo. I have not worked with PHP in years.

**Comment by simonschaufi** [comment]
ok cool, then you can either transfer me the repository or give me full access to it please.

**Comment by earelin** [comment]
I have sent you an invite

**Comment by simonschaufi** [comment]
Thank you
